---
title: "git_01"
author: "Kelly Acevedo"
date: "Spring 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
Little Birds are dining
Warily and well,
Hid in mossy cell:
Hid, I say, by waiters
Gorgeous in their gaiters -
I've a Tale to tell. 

## Second Verse
Little Birds are feeding
Justices with jam,
Rich in frizzled ham:
Rich, I say, in oysters
Haunting shady cloisters -
That is what I am. 

## Third Verse
"The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night.

The moon was shining sulkily,
      Because she thought the sun
Had got no business to be there
      After the day was done —
"It's very rude of him," she said,
      "To come and spoil the fun."

## Last Verse
In every gleam, a universe resides,
A language silent, yet it confides.
Upon lips curved in arcs of grace,
A symphony of joy finds its place.

In smiles, the sun's warm embrace,
Paints the world with hues of grace.
Through laughter's dance, hearts unite,
In shared moments, pure and bright.

A smile, a beacon in the night,
Guiding souls with gentle light.
It speaks of love, of hope, of peace,
A tender touch that will not cease.

In every smile, a story told,
Of battles fought and dreams unfold.
It whispers secrets, untold and wise,
Reflecting beauty in endless skies.

So let us cherish each smile we meet,
For in its warmth, life's treasures fleet.
In simple gestures, we find our way,
To brighter tomorrows, come what may.